package ${unitTestPackageName};

import ${modelPackageName}.${modelSimpleName};
import ${repositoryPackageName}.${repositorySimpleName};

import org.junit.Assert;
import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;

/**
* Generated by codegen.
*/
public class ${unitTestSimpleName} extends AbstractRepositoryTest{

    @Autowired
    protected ${repositorySimpleName} ${repositorySimpleName?uncap_first};

    @Test
    public void testSave(){

        ${modelSimpleName} ${modelSimpleName?uncap_first} = new ${modelSimpleName}();
<#if fieldTestValueTemplates??>
    <#list fieldTestValueTemplates as field>
        ${modelSimpleName?uncap_first}.set${field.name?cap_first}("${field.testValueIn}");
    </#list>
</#if>

        ${repositorySimpleName?uncap_first}.save(${modelSimpleName?uncap_first});

        ${modelSimpleName} result = ${repositorySimpleName?uncap_first}.findOne(${modelSimpleName?uncap_first}.getId());
        Assert.assertNotNull(result);
<#if fieldTestValueTemplates??>
    <#list fieldTestValueTemplates as field>
        Assert.assertEquals("${field.testValueOut}", ${modelSimpleName?uncap_first}.get${field.name?cap_first}());
    </#list>
</#if>

    }
}
